### ISSUE TITLE
OpenSecrets gem at RubyGems still reflecting old version

### ISSUE THREAD

**Issue by sunraa** [grempe/opensecrets#2]
Hello

I've installed the 'open secrets' gem successfully. 

I'm trying to [run the example](https://github.com/grempe/opensecrets/blob/master/examples/example.rb) from within `irb` and I receive the following error: 
```ruby
2.1.5 :006 > member = OpenSecrets::Member.new
NoMethodError: undefined method `blank?' for "---myapikey---":String
from /Users/######/.rvm/gems/ruby-2.1.5/gems/opensecrets-0.0.5/lib/opensecrets.rb:21:in `initialize'
	from (irb):6:in `new'
	from (irb):6
	from /Users/######/.rvm/rubies/ruby-2.1.5/bin/irb:11:in `<main>'
```

When I open up `open secrets.rb` and look at line 21, it does not reflect the [current version of the code](https://github.com/grempe/opensecrets/blob/master/lib/opensecrets.rb). Could the gem be updated and pushed out? 

Thanks in advance.

**Comment by grempe** [comment]
Hi.

Well, I've dusted off this gem, fixed some API issues, added all remaining new API endpoints as they are documented today, updated the Gem infrastructure to be more modern, and cleaned up the docs and examples a little.  Your issue should be solved now.

See Commit:
b35b2268bd987bddc708349b4267d32ce7428bfb

I've pushed this new code as v1.0.0 to RubyGems.
https://rubygems.org/gems/opensecrets

Cheers,

Glenn
